In [27]:
import numpy as np

In [36]:
np.random.seed(7)
#A = np.random.rand(4,4)
A = np.diag((1, 2, 3))

In [37]:
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [39]:
eigenvalues

array([1., 2., 3.])

In [40]:
eigenvectors

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
assert np.allclose(A @ eigenvectors[0], eigenvalues[0] * eigenvectors[0], 1e-4)

In [45]:
A_ = [np.outer(eigenvectors[i], eigenvectors[i])*eigenvalues[i] for i in range(len(eigenvalues))]

In [46]:
A__ = np.sum(A_, axis=0)

In [47]:
A__

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])