In [39]:
# matrix generator:

# Step 1: Choose real eigenvalues
eigenvalues = np.array([2, 3, -1, 4]) 
P = np.random.rand(4, 4)  # Random 4x4 matrix
while np.linalg.det(P) == 0:  # Ensure P is invertible
    P = np.random.rand(4, 4)

D = np.diag(eigenvalues)
A = P @ D @ np.linalg.inv(P)

print("Generated matrix A:")
print(A)

eigvals, eigvecs = np.linalg.eig(A)
eigvecs = eigvecs / np.linalg.norm(eigvecs, axis=0).reshape(1, -1)

for i in range(4):
    print(eigvecs[:,i], " with eigen val: ", eigvals[i])

Generated matrix A:
[[-45.76359154   9.80683409  38.6704949    7.13419489]
 [-21.30285986   7.97699321  15.16197295   3.52787002]
 [-44.30346404   8.65403265  38.70188973   6.44614701]
 [-30.95693576   7.02172932  23.12005911   7.0847086 ]]
[0.58732143 0.35279618 0.49115464 0.53791775]  with eigen val:  -0.999999999999801
[-0.2709694  -0.80982184 -0.0477366  -0.51815575]  with eigen val:  4.000000000000049
[0.47406364 0.7720142  0.36128803 0.22074581]  with eigen val:  2.9999999999998512
[0.37116425 0.14696456 0.25890557 0.87954899]  with eigen val:  1.9999999999999298


In [52]:
# objective find first n eigenvectors using power iteration
A_ = A.copy()
first = None
eigenvectors = []
for j in range(3):
    ev = np.random.normal(size=4)
    if first is not None:
        ev = ev - first * np.inner(ev, first)
    ev /= np.linalg.norm(ev)
    for i in range(50):
        tmp = A_ @ ev
        for prev_ev in eigenvectors:
            tmp -= prev_ev * np.dot(tmp, prev_ev)
        ev /= np.linalg.norm(ev)
        ev = tmp / np.linalg.norm(tmp)
        if first is not None:
            print(np.inner(first, ev))
    lam = ev @ (A @ ev)
    print("{}-th Eigenvector of A: ".format(j), ev, " E.-value: ",lam)
    eigenvectors.append(ev)
    # remove ev from A:
    tmp = np.outer(ev, A_ @ ev)
    A_ = A_ -tmp

0-th Eigenvector of A:  [-0.27096924 -0.80982181 -0.04773638 -0.51815591]  E.-value:  4.000000615397149
1-th Eigenvector of A:  [-0.50354656 -0.11847192 -0.68598986  0.51168661]  E.-value:  2.9999993849457987
2-th Eigenvector of A:  [ 0.30317059 -0.55599343  0.3774485   0.67564157]  E.-value:  1.9999999996570188
